void derivative_weights(double z,double *x, int n, int nd, int m, double *c);
void init_stats();
double get_stats(FILE *infile=NULL);
void line_array(int,int,int,int,int*);
//void find_max(double [NX][NY][NZ], int*, double*, double*);
void rescale_pert(double max1, double max2, double scale1, double scale2, int * arr, bool upper, bool lower);
void rescale_pert2(double,double);
double find_max2(double *);
//int find_max3(double[NX][NY][NZ],int);
double pivot_coriolis(double,int,int);
void print_max_arrays(int);
int get_point_from_lat(double);
int get_point_from_lon(double);
int get_point_from_height(double);
double cos_profile(double pl,double ph,double frac,double shift);
double frac_distance(int index,int low,int high);
//double frac_distance(double index,double low,double high);
double stable_time_step(double delta,double vel);
double convert_z_to_k(double zf,double z0,double lev,double dzp);
double convert_k_to_z(double ki,double z0,double lev,double dzp);
void print_time_estimates(int total_cputime,int total_walltime,int timer_counter);
